export const SET_POKEMONS = 'SET_POKEMONS'
export const SET_SELECTED = 'SET_SELECTED'
export const SET_RIVAL = 'SET_RIVAL'
export const ATTACK = 'ATTACK'
export const CHANGE_TURN = 'CHANGE_TURN'
export const RIVAL_ATTACK = 'RIVAL_ATTACK'